name: Deploy

on:
    push:
        paths-ignore:
            - "resources/*"
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build
              uses: actions/setup-node@v1
            - run: npm install
            - run: npm run build

            - name: copy files via scp
              uses: appleboy/scp-action@master
              with:
                  host: vaporware.ga
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  source: "dist/."
                  target: /var/www/vaporware.ga/flightsim/
                  strip_components: 1
